### ISSUE TITLE
Wasm OOM error

### ISSUE THREAD

**Issue by EmNudge** [kdheepak/remark-svgbob#3]
It seems there's an issue with our latest wasm build parsing multiple svgbob diagrams in a document. We get what looks like a memory-related error. 

I investigated it a bit this morning although it's been annoying to test since the error removes all input from my terminal (so I can't see the actual error message). I'll keep investigating for now.

**Comment by EmNudge** [comment]
Made some progress. I assumed it was related to an out of memory error since it seemed to occur when calling render multiple times, but it actually seems to be related to calling the `getRenderer` multiple times as in - when we call `WebAssembly.instantiate` more than once with the same buffer. 

I was using a local variable to ensure this doesn't happen, but this module is getting refreshed in certain contexts (tests and when running the remark plugin for some reason) which resets this variable. 

I have some ideas which I can test out later tonight.

**Comment by kdheepak** [comment]
Awesome! Thanks for looking into this! If you want to be added as a maintainer to this package let me know!

**Comment by EmNudge** [comment]
Yeah, being added as a maintainer might be easier to make branches directly on the repo instead of syncing my fork each time.

**Comment by kdheepak** [comment]
I added you to the GitHub repo, you should have received an invite. Feel free to make another PR if you wish to add your name to the contributors in the `package.json` file.
