### ISSUE TITLE
Not working with @next/mdx

### ISSUE THREAD

**Issue by m5p3nc3r** [kdheepak/remark-svgbob#5]
I configure the plugin like this:

```javascript
import nextMDX from "@next/mdx";
import remarkSVGBob from "remark-svgbob";

const withMDX = nextMDX({
  extension: /\.mdx?$/,
  options: {
    remarkPlugins: [remarkSVGBob],
    rehypePlugins: [],
  },
});

const nextConfig = {
  pageExtensions: ["js", "jsx", "mdx", "ts", "tsx"],
};

export default withMDX(nextConfig);
```

With this configuration, I can see that the `svgbob` code block is being detected in my markdown, and that the ASCII is being converted into what looks like a sensible SVG block.

But if I am processing any pages with svgbob content, I get the following error

```
 ⨯ ./src/app/page.mdx
Error: page.mdx:Error: Cannot handle unknown node `raw`
Import trace for requested module:
./src/app/page.mdx
```

Is there something else that needs to be done to this plugin to make it compatible with the next/mdx framework?

**Comment by m5p3nc3r** [comment]
Hey - I have spent a bit more time looking into this.  I can fix some of the issue by adding the rehype-raw plugin, but this causes me some additional issues.  The compiler gives this error:

Error: page.mdx:Error: Cannot compile `mdxjsEsm` node. It looks like you are using MDX nodes with `hast-util-raw` (or `rehype-raw`). If you use this because you are using remark or rehype plugins that inject `'html'` nodes, then please raise an issue with that plugin, as its a bad and slow idea. If you use this because you are using markdown syntax, then you have to configure this utility (or plugin) to pass through these nodes (see `passThrough` in docs), but you can also migrate to use the MDX syntax.

Any pointers on how to move forward with this would be appreciated.

**Comment by m5p3nc3r** [comment]
I have solved this issue for my use-case, I thought I would share the details here as it might be useful.

I modified `remarkPlugin()`  to base64 encode the svg and add it inline as a data src to an img tag.  The code looks something like this:

```js
visit(tree, "code", (node, index, parent) => {
      if (node.lang === "svgbob") {
        const svg = render(node.value);

        const buffer = Buffer.from(svg, "utf8");
        const base64SVG = buffer.toString("base64");
        const imgSrc = `data:image/svg+xml;base64,${base64SVG}`;

        const image = {
          type: "mdxJsxFlowElement",
          name: "img",
          attributes: [
            { type: "mdxJsxAttribute", name: "src", value: imgSrc },
            { type: "mdxJsxAttribute", name: "alt", value: "svgbob" },
          ],
          children: [],
        };

        parent.children.splice(index, 1, image);
      }
    });
```

As I say, this works for me and has the added advantage that it is no longer working with `raw` nodes, so you don't need to configure `rehype-raw` to pass raw html through the rehype processing.

If this looks useful, I am more than happy to create a PR for the changes.

**Comment by kdheepak** [comment]
That works for me! Thank you for pushing on this! If you'd like to submit a PR that'd be great!

**Comment by m5p3nc3r** [comment]
I have the code implemented now, but the tests are failing with the error `Error: Cannot handle unknown node 'mdxJsxFlowElement'`.  The SVG generation is working fine, but I don't think the test runner is configured correctly.

Do you know how to fix this?

**Comment by m5p3nc3r** [comment]
Never mind - I have it working now by ensuring that remarkMDX plugin is added to the remark processor.

I'll submit a PR now.

**Comment by m5p3nc3r** [comment]
I'm not 100% happy with the way the fix is implemented at the moment.  The style is baked into the img data, and I can't see a way you can change it from the page css.  This causes issues with things like dark mode etc.
I'm exploring the option of extracting the style info from the svg and adding it to the containing img to see if that fixed the issue.

**Comment by m5p3nc3r** [comment]
I have had a little more progress with this now.  I can pass the raw SVG through rehype (there are some edge cases, but I'll look into these).
On the styling front - I'm starting to lean towards having the styling external to the svg itself, as this lends better to use-cases such as dark mode etc.
@kdheepak Can you let me know your thoughts on this please?

**Comment by kdheepak** [comment]
> I'm starting to lean towards having the styling external to the svg itself, as this lends better to use-cases such as dark mode etc.

I like this idea! Let me know if you'd like to be added as a collaborator to the repo, and you can merge your own PRs that way and I wouldn't be a blocker (I've had little time for open source unfortunately).

**Comment by kdheepak** [comment]
cc @EmNudge who is also a maintainer for this repo.

**Comment by m5p3nc3r** [comment]
Hi guys - I believe I am happy with the code now.  Can you check out #7.  There is an example of how the external stylesheet is a good thing in the PR.

Benefits are that you no longer need to use any 'raw' mode, and you have complete control over the styling of the element in your site.

**Comment by m5p3nc3r** [comment]
Thanks for merging the code - how about this for a suggestion.  There are three modes for the plugin
- raw (original) where it places the svg with style inline with the output html.  This will require the user configure remark properly so it accepts raw html
- mdx, where it generates correct inline svg to that will be parsed by a standard rehype pipeline.  But it is up to the end user to ensure the stylesheet is included (my preferred version as it gives me the best styling control)
- base64 data url, where the svg is encoded as a data url, with style included.  This is the easiest to use, but gives the end user less control as they are unable to modify the presentation style of the svg content.

All versions of this code now exist, we would just need to add the configuration part.  Your thoughts?

**Comment by m5p3nc3r** [comment]
FYI - I have used this plugin in my personal blog post now.  You can see the results at https://m5p3nc3r.co.uk/projects/opensource/remark-svgbob.

I'll close this issue now, but do think there could be use for the comments I made in my previous not to this issue..
